<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Documenten;

use DateTimeInterface;
use Woweb\Zgw\Data\Generated\Documenten\Enums\Status;
use Woweb\Zgw\Data\Generated\Documenten\Enums\Vertrouwelijkheidaanduiding;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a EnkelvoudigInformatieObject.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write documenten:EnkelvoudigInformatieObject
 */
final class EnkelvoudigInformatieObjectWrite extends WriteBuilder
{
    public function identificatie(?string $value): static
    {
        return $this->set('identificatie', $value);
    }

    public function bronorganisatie(?string $value): static
    {
        return $this->set('bronorganisatie', $value);
    }

    public function creatiedatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('creatiedatum', $this->date($value));
    }

    public function titel(?string $value): static
    {
        return $this->set('titel', $value);
    }

    public function vertrouwelijkheidaanduiding(Vertrouwelijkheidaanduiding|string|int|null $value): static
    {
        return $this->set('vertrouwelijkheidaanduiding', $this->enum($value));
    }

    public function isGereedVoorPublicatie(?bool $value): static
    {
        return $this->set('isGereedVoorPublicatie', $value);
    }

    public function tonenAanInitiator(?bool $value): static
    {
        return $this->set('tonenAanInitiator', $value);
    }

    public function auteur(?string $value): static
    {
        return $this->set('auteur', $value);
    }

    public function status(Status|string|int|null $value): static
    {
        return $this->set('status', $this->enum($value));
    }

    public function inhoudIsVervallen(?bool $value): static
    {
        return $this->set('inhoudIsVervallen', $value);
    }

    public function formaat(?string $value): static
    {
        return $this->set('formaat', $value);
    }

    public function taal(?string $value): static
    {
        return $this->set('taal', $value);
    }

    public function bestandsnaam(?string $value): static
    {
        return $this->set('bestandsnaam', $value);
    }

    public function inhoud(Reference|string|null $value): static
    {
        return $this->set('inhoud', $this->reference($value));
    }

    public function bestandsomvang(?int $value): static
    {
        return $this->set('bestandsomvang', $value);
    }

    public function link(Reference|string|null $value): static
    {
        return $this->set('link', $this->reference($value));
    }

    public function beschrijving(?string $value): static
    {
        return $this->set('beschrijving', $value);
    }

    public function ontvangstdatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('ontvangstdatum', $this->date($value));
    }

    public function verzenddatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('verzenddatum', $this->date($value));
    }

    public function indicatieGebruiksrecht(?bool $value): static
    {
        return $this->set('indicatieGebruiksrecht', $value);
    }

    public function verschijningsvorm(?string $value): static
    {
        return $this->set('verschijningsvorm', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function ondertekening(?array $value): static
    {
        return $this->set('ondertekening', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function integriteit(?array $value): static
    {
        return $this->set('integriteit', $value);
    }

    public function informatieobjecttype(Reference|string|null $value): static
    {
        return $this->set('informatieobjecttype', $this->reference($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function trefwoorden(?array $value): static
    {
        return $this->set('trefwoorden', $value);
    }
}
