<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Documenten;

use DateTimeInterface;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Gebruiksrechten.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write documenten:Gebruiksrechten
 */
final class GebruiksrechtenWrite extends WriteBuilder
{
    public function informatieobject(Reference|string|null $value): static
    {
        return $this->set('informatieobject', $this->reference($value));
    }

    public function startdatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('startdatum', $this->dateTime($value));
    }

    public function einddatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('einddatum', $this->dateTime($value));
    }

    public function omschrijvingVoorwaarden(?string $value): static
    {
        return $this->set('omschrijvingVoorwaarden', $value);
    }
}
