<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Documenten;

use Woweb\Zgw\Data\Generated\Documenten\Enums\ObjectType;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a ObjectInformatieObject.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write documenten:ObjectInformatieObject
 */
final class ObjectInformatieObjectWrite extends WriteBuilder
{
    public function informatieobject(Reference|string|null $value): static
    {
        return $this->set('informatieobject', $this->reference($value));
    }

    public function object(Reference|string|null $value): static
    {
        return $this->set('object', $this->reference($value));
    }

    public function objectType(ObjectType|string|int|null $value): static
    {
        return $this->set('objectType', $this->enum($value));
    }
}
