<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Documenten;

use DateTimeInterface;
use Woweb\Zgw\Data\Generated\Documenten\Enums\AardRelatie;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Verzending.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write documenten:Verzending
 */
final class VerzendingWrite extends WriteBuilder
{
    public function betrokkene(Reference|string|null $value): static
    {
        return $this->set('betrokkene', $this->reference($value));
    }

    public function informatieobject(Reference|string|null $value): static
    {
        return $this->set('informatieobject', $this->reference($value));
    }

    public function aardRelatie(AardRelatie|string|int|null $value): static
    {
        return $this->set('aardRelatie', $this->enum($value));
    }

    public function toelichting(?string $value): static
    {
        return $this->set('toelichting', $value);
    }

    public function ontvangstdatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('ontvangstdatum', $this->date($value));
    }

    public function verzenddatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('verzenddatum', $this->date($value));
    }

    public function contactPersoon(Reference|string|null $value): static
    {
        return $this->set('contactPersoon', $this->reference($value));
    }

    public function contactpersoonnaam(?string $value): static
    {
        return $this->set('contactpersoonnaam', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function binnenlandsCorrespondentieadres(?array $value): static
    {
        return $this->set('binnenlandsCorrespondentieadres', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function buitenlandsCorrespondentieadres(?array $value): static
    {
        return $this->set('buitenlandsCorrespondentieadres', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function correspondentiePostadres(?array $value): static
    {
        return $this->set('correspondentiePostadres', $value);
    }

    public function faxnummer(?string $value): static
    {
        return $this->set('faxnummer', $value);
    }

    public function emailadres(?string $value): static
    {
        return $this->set('emailadres', $value);
    }

    public function mijnOverheid(?bool $value): static
    {
        return $this->set('mijnOverheid', $value);
    }

    public function telefoonnummer(?string $value): static
    {
        return $this->set('telefoonnummer', $value);
    }
}
