<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Catalogi;

use DateInterval;
use DateTimeInterface;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a BesluitType.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write catalogi:BesluitType
 */
final class BesluitTypeWrite extends WriteBuilder
{
    public function catalogus(Reference|string|null $value): static
    {
        return $this->set('catalogus', $this->reference($value));
    }

    public function omschrijving(?string $value): static
    {
        return $this->set('omschrijving', $value);
    }

    public function omschrijvingGeneriek(?string $value): static
    {
        return $this->set('omschrijvingGeneriek', $value);
    }

    public function besluitcategorie(?string $value): static
    {
        return $this->set('besluitcategorie', $value);
    }

    public function reactietermijn(DateInterval|string|null $value): static
    {
        return $this->set('reactietermijn', $this->duration($value));
    }

    public function publicatieIndicatie(?bool $value): static
    {
        return $this->set('publicatieIndicatie', $value);
    }

    public function publicatietekst(?string $value): static
    {
        return $this->set('publicatietekst', $value);
    }

    public function publicatietermijn(DateInterval|string|null $value): static
    {
        return $this->set('publicatietermijn', $this->duration($value));
    }

    public function toelichting(?string $value): static
    {
        return $this->set('toelichting', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function informatieobjecttypen(?array $value): static
    {
        return $this->set('informatieobjecttypen', $value);
    }

    public function beginGeldigheid(DateTimeInterface|string|null $value): static
    {
        return $this->set('beginGeldigheid', $this->date($value));
    }

    public function eindeGeldigheid(DateTimeInterface|string|null $value): static
    {
        return $this->set('eindeGeldigheid', $this->date($value));
    }

    public function beginObject(DateTimeInterface|string|null $value): static
    {
        return $this->set('beginObject', $this->date($value));
    }

    public function eindeObject(DateTimeInterface|string|null $value): static
    {
        return $this->set('eindeObject', $this->date($value));
    }
}
