<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Catalogi;

use DateTimeInterface;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Catalogus.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write catalogi:Catalogus
 */
final class CatalogusWrite extends WriteBuilder
{
    public function domein(?string $value): static
    {
        return $this->set('domein', $value);
    }

    public function rsin(?string $value): static
    {
        return $this->set('rsin', $value);
    }

    public function contactpersoonBeheerNaam(?string $value): static
    {
        return $this->set('contactpersoonBeheerNaam', $value);
    }

    public function contactpersoonBeheerTelefoonnummer(?string $value): static
    {
        return $this->set('contactpersoonBeheerTelefoonnummer', $value);
    }

    public function contactpersoonBeheerEmailadres(?string $value): static
    {
        return $this->set('contactpersoonBeheerEmailadres', $value);
    }

    public function naam(?string $value): static
    {
        return $this->set('naam', $value);
    }

    public function versie(?string $value): static
    {
        return $this->set('versie', $value);
    }

    public function begindatumVersie(DateTimeInterface|string|null $value): static
    {
        return $this->set('begindatumVersie', $this->date($value));
    }
}
