<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Catalogi;

use DateTimeInterface;
use Woweb\Zgw\Data\Generated\Catalogi\Enums\Archiefnominatie;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a ResultaatType.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write catalogi:ResultaatType
 */
final class ResultaatTypeWrite extends WriteBuilder
{
    public function zaaktype(Reference|string|null $value): static
    {
        return $this->set('zaaktype', $this->reference($value));
    }

    public function omschrijving(?string $value): static
    {
        return $this->set('omschrijving', $value);
    }

    public function resultaattypeomschrijving(Reference|string|null $value): static
    {
        return $this->set('resultaattypeomschrijving', $this->reference($value));
    }

    public function selectielijstklasse(Reference|string|null $value): static
    {
        return $this->set('selectielijstklasse', $this->reference($value));
    }

    public function toelichting(?string $value): static
    {
        return $this->set('toelichting', $value);
    }

    public function archiefnominatie(Archiefnominatie|string|int|null $value): static
    {
        return $this->set('archiefnominatie', $this->enum($value));
    }

    public function archiefactietermijn(?string $value): static
    {
        return $this->set('archiefactietermijn', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function brondatumArchiefprocedure(?array $value): static
    {
        return $this->set('brondatumArchiefprocedure', $value);
    }

    public function procesobjectaard(?string $value): static
    {
        return $this->set('procesobjectaard', $value);
    }

    public function catalogus(Reference|string|null $value): static
    {
        return $this->set('catalogus', $this->reference($value));
    }

    public function beginGeldigheid(DateTimeInterface|string|null $value): static
    {
        return $this->set('beginGeldigheid', $this->date($value));
    }

    public function eindeGeldigheid(DateTimeInterface|string|null $value): static
    {
        return $this->set('eindeGeldigheid', $this->date($value));
    }

    public function beginObject(DateTimeInterface|string|null $value): static
    {
        return $this->set('beginObject', $this->date($value));
    }

    public function eindeObject(DateTimeInterface|string|null $value): static
    {
        return $this->set('eindeObject', $this->date($value));
    }

    public function indicatieSpecifiek(?bool $value): static
    {
        return $this->set('indicatieSpecifiek', $value);
    }

    public function procestermijn(?string $value): static
    {
        return $this->set('procestermijn', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function besluittypen(?array $value): static
    {
        return $this->set('besluittypen', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function informatieobjecttypen(?array $value): static
    {
        return $this->set('informatieobjecttypen', $value);
    }
}
