<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Catalogi;

use DateInterval;
use DateTimeInterface;
use Woweb\Zgw\Data\Generated\Catalogi\Enums\IndicatieInternOfExtern;
use Woweb\Zgw\Data\Generated\Catalogi\Enums\Vertrouwelijkheidaanduiding;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a ZaakType.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write catalogi:ZaakType
 */
final class ZaakTypeWrite extends WriteBuilder
{
    public function identificatie(?string $value): static
    {
        return $this->set('identificatie', $value);
    }

    public function omschrijving(?string $value): static
    {
        return $this->set('omschrijving', $value);
    }

    public function omschrijvingGeneriek(?string $value): static
    {
        return $this->set('omschrijvingGeneriek', $value);
    }

    public function vertrouwelijkheidaanduiding(Vertrouwelijkheidaanduiding|string|int|null $value): static
    {
        return $this->set('vertrouwelijkheidaanduiding', $this->enum($value));
    }

    public function doel(?string $value): static
    {
        return $this->set('doel', $value);
    }

    public function aanleiding(?string $value): static
    {
        return $this->set('aanleiding', $value);
    }

    public function toelichting(?string $value): static
    {
        return $this->set('toelichting', $value);
    }

    public function indicatieInternOfExtern(IndicatieInternOfExtern|string|int|null $value): static
    {
        return $this->set('indicatieInternOfExtern', $this->enum($value));
    }

    public function handelingInitiator(?string $value): static
    {
        return $this->set('handelingInitiator', $value);
    }

    public function onderwerp(?string $value): static
    {
        return $this->set('onderwerp', $value);
    }

    public function handelingBehandelaar(?string $value): static
    {
        return $this->set('handelingBehandelaar', $value);
    }

    public function doorlooptijd(DateInterval|string|null $value): static
    {
        return $this->set('doorlooptijd', $this->duration($value));
    }

    public function servicenorm(DateInterval|string|null $value): static
    {
        return $this->set('servicenorm', $this->duration($value));
    }

    public function opschortingEnAanhoudingMogelijk(?bool $value): static
    {
        return $this->set('opschortingEnAanhoudingMogelijk', $value);
    }

    public function verlengingMogelijk(?bool $value): static
    {
        return $this->set('verlengingMogelijk', $value);
    }

    public function verlengingstermijn(DateInterval|string|null $value): static
    {
        return $this->set('verlengingstermijn', $this->duration($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function trefwoorden(?array $value): static
    {
        return $this->set('trefwoorden', $value);
    }

    public function publicatieIndicatie(?bool $value): static
    {
        return $this->set('publicatieIndicatie', $value);
    }

    public function publicatietekst(?string $value): static
    {
        return $this->set('publicatietekst', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function verantwoordingsrelatie(?array $value): static
    {
        return $this->set('verantwoordingsrelatie', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function productenOfDiensten(?array $value): static
    {
        return $this->set('productenOfDiensten', $value);
    }

    public function selectielijstProcestype(Reference|string|null $value): static
    {
        return $this->set('selectielijstProcestype', $this->reference($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function referentieproces(?array $value): static
    {
        return $this->set('referentieproces', $value);
    }

    public function verantwoordelijke(?string $value): static
    {
        return $this->set('verantwoordelijke', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function broncatalogus(?array $value): static
    {
        return $this->set('broncatalogus', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function bronzaaktype(?array $value): static
    {
        return $this->set('bronzaaktype', $value);
    }

    public function catalogus(Reference|string|null $value): static
    {
        return $this->set('catalogus', $this->reference($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function besluittypen(?array $value): static
    {
        return $this->set('besluittypen', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function deelzaaktypen(?array $value): static
    {
        return $this->set('deelzaaktypen', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function deelzaaktypeIdentificaties(?array $value): static
    {
        return $this->set('deelzaaktypeIdentificaties', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function gerelateerdeZaaktypen(?array $value): static
    {
        return $this->set('gerelateerdeZaaktypen', $value);
    }

    public function beginGeldigheid(DateTimeInterface|string|null $value): static
    {
        return $this->set('beginGeldigheid', $this->date($value));
    }

    public function eindeGeldigheid(DateTimeInterface|string|null $value): static
    {
        return $this->set('eindeGeldigheid', $this->date($value));
    }

    public function beginObject(DateTimeInterface|string|null $value): static
    {
        return $this->set('beginObject', $this->date($value));
    }

    public function eindeObject(DateTimeInterface|string|null $value): static
    {
        return $this->set('eindeObject', $this->date($value));
    }

    public function versiedatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('versiedatum', $this->date($value));
    }
}
