<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Catalogi;

use Woweb\Zgw\Data\Generated\Catalogi\Enums\Richting;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a ZaakTypeInformatieObjectType.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write catalogi:ZaakTypeInformatieObjectType
 */
final class ZaakTypeInformatieObjectTypeWrite extends WriteBuilder
{
    public function zaaktype(Reference|string|null $value): static
    {
        return $this->set('zaaktype', $this->reference($value));
    }

    public function informatieobjecttype(?string $value): static
    {
        return $this->set('informatieobjecttype', $value);
    }

    public function volgnummer(?int $value): static
    {
        return $this->set('volgnummer', $value);
    }

    public function richting(Richting|string|int|null $value): static
    {
        return $this->set('richting', $this->enum($value));
    }

    public function statustype(Reference|string|null $value): static
    {
        return $this->set('statustype', $this->reference($value));
    }
}
