<?php

declare(strict_types=1);

namespace Woweb\Zgw\Dev\Dto;

use Illuminate\Support\Str;
use RuntimeException;
use Woweb\Zgw\Tests\Contract\Support\ReleaseMatrix;
use Woweb\Zgw\Tests\Contract\Support\SpecModel;

/**
 * Generates the typed read DTOs from the pinned ZGW OpenAPI specs.
 *
 * The generator is a require-dev tool: its output (the DTOs, nested value DTOs and enums) is
 * committed, so the runtime never carries the generator. It reads the same spec fixtures the
 * contract suite pins, builds a superset of fields across releases, annotates per-field @since
 * for fields that did not exist in the earliest supported release, and picks a cast per field
 * from the field's type, format, enum or object reference.
 *
 * The "Data" namespace must not depend on anything in this dev namespace; the dependency only
 * runs at generation time.
 */
final class DtoGenerator
{
    private const HEADER = '// This file is generated by `composer dto:generate`. Do not edit it by hand.';

    /** @var array<string, SpecModel> keyed by release label. */
    private array $specsByRelease = [];

    /** @var list<string> release labels sorted oldest first (for example "1.5", "1.6", "1.7"). */
    private array $releaseOrder = [];

    private SpecModel $latest;

    /** @var array<string, bool> object schema name => isRoot, queued for generation. */
    private array $objectQueue = [];

    /** @var array<string, bool> object schema names already generated. */
    private array $objectDone = [];

    /** @var array<string, bool> enum schema names queued. */
    private array $enumQueue = [];

    /** @var array<string, string> written file path => contents. */
    private array $files = [];

    /**
     * @param  string  $component  ZGW component the schemas live in (for example "zaken").
     * @param  list<string>  $rootSchemas  Root resource schema names for this component (each becomes a {Schema}Data DTO).
     * @param  string  $namespace  Base namespace for the generated objects of this component.
     * @param  string  $outDir  Directory the objects are written to.
     * @param  list<string>  $opaque  Object schema names kept as raw arrays rather than generated DTOs.
     * @param  array<string, array{type: class-string, cast: class-string}>  $valueObjects  Schema
     *                                                                                      names mapped to a hand-written value object and its cast (for stable, standardised
     *                                                                                      structures such as GeoJSON that are modelled as value objects, not generated DTOs).
     * @param  array<string, array{only?: list<string>, fallbackToRaw?: bool}>  $discriminators  Per
     *                                                                                           discriminated schema, which discriminator values get a typed sub-DTO (`only`,
     *                                                                                           default all mapped values) and whether an unmapped value keeps the raw sub-object
     *                                                                                           instead of resolving to null (`fallbackToRaw`, default false). Discriminators are
     *                                                                                           detected from the specs; this only narrows the typed set and the fallback mode.
     * @param  string  $baseNamespace  Root namespace of all generated components, so an expanded
     *                                 field can link to a DTO in another component's namespace.
     * @param  array<string, list<string>>  $rootSchemasByComponent  Root schema names per component,
     *                                                               used to resolve cross-component external $refs (a `zaaktype` in an expanded zaak points at
     *                                                               the catalogi ZaakType) to the generated DTO, degrading to a raw array when unresolvable.
     */
    public function __construct(
        private readonly string $component,
        private readonly array $rootSchemas,
        private readonly string $namespace,
        private readonly string $outDir,
        private readonly array $opaque = [],
        private readonly array $valueObjects = [],
        private readonly array $discriminators = [],
        private readonly string $baseNamespace = '',
        private readonly array $rootSchemasByComponent = [],
    ) {}

    /**
     * @return list<string> the paths written.
     */
    public function generate(): array
    {
        $this->loadSpecs();

        foreach ($this->rootSchemas as $root) {
            $this->objectQueue[$root] = true;
        }

        while ($this->objectQueue !== []) {
            $name = array_key_first($this->objectQueue);
            $isRoot = $this->objectQueue[$name];
            unset($this->objectQueue[$name]);

            if (isset($this->objectDone[$name])) {
                continue;
            }

            $this->objectDone[$name] = true;
            $this->generateObject($name, $isRoot);
        }

        foreach (array_keys($this->enumQueue) as $enumSchema) {
            $this->generateEnum($enumSchema);
        }

        $paths = [];

        foreach ($this->files as $path => $contents) {
            $dir = dirname($path);
            if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
                throw new RuntimeException("Could not create directory [{$dir}].");
            }
            file_put_contents($path, $contents);
            $paths[] = $path;
        }

        sort($paths);

        return $paths;
    }

    private function loadSpecs(): void
    {
        foreach (array_keys(ReleaseMatrix::releases()) as $release) {
            $file = ReleaseMatrix::specFile($release, $this->component);
            if ($file === null) {
                continue;
            }
            $this->specsByRelease[$release] = SpecModel::fromFile($file);
            $this->releaseOrder[] = $release;
        }

        if ($this->specsByRelease === []) {
            throw new RuntimeException(
                "No spec fixtures found for component [{$this->component}]. Run `composer contract:fetch` first."
            );
        }

        sort($this->releaseOrder);
        $this->latest = $this->specsByRelease[$this->releaseOrder[count($this->releaseOrder) - 1]];
    }

    private function generateObject(string $schemaName, bool $isRoot): void
    {
        // The merged properties of this schema per release, so the DTO can be a true superset
        // across releases and carry per-field version metadata.
        $perRelease = [];
        foreach ($this->releaseOrder as $release) {
            $schema = $this->specsByRelease[$release]->componentSchema($schemaName);
            if ($schema !== null) {
                $perRelease[$release] = $this->mergedProperties($this->specsByRelease[$release], $schema);
            }
        }

        if ($perRelease === []) {
            throw new RuntimeException("Schema [{$schemaName}] not found in any {$this->component} spec.");
        }

        // Union of field names: newest release first (so the order follows the current spec), then
        // any field that only exists in an older release appended after.
        $order = [];
        foreach (array_reverse($this->releaseOrder) as $release) {
            foreach (array_keys($perRelease[$release] ?? []) as $field) {
                // _expand is sourced from the {Schema}Expanded variant (appendExpandField), not from
                // the base properties: older releases inline it on the base, newer ones move it to
                // the Expanded schema, so the inline copy is skipped to keep one authoritative field.
                if ($field === '_expand' || in_array($field, $order, true)) {
                    continue;
                }

                $order[] = $field;
            }
        }

        $className = $isRoot ? $schemaName.'Data' : $schemaName;

        $fields = [];
        $casts = [];
        $imports = ['Woweb\Zgw\Data\Data'];

        foreach ($order as $field) {
            $present = array_values(array_filter(
                $this->releaseOrder,
                static fn (string $release): bool => isset($perRelease[$release][$field]),
            ));

            // Type and cast come from the newest release that still defines the field.
            $sourceRelease = $present[count($present) - 1];
            $descriptor = $this->describe($perRelease[$sourceRelease][$field], $this->specsByRelease[$sourceRelease]);

            $since = $present[0] === $this->releaseOrder[0] ? null : $present[0];
            $removedIn = $this->removedIn($present);

            $fields[] = $this->renderField($field, $descriptor, $since, $removedIn);

            foreach ($descriptor['imports'] as $import) {
                $imports[] = $import;
            }

            if ($descriptor['cast'] !== null && $descriptor['castImport'] !== null) {
                $casts[$field] = $descriptor['cast'];
                $imports[] = $descriptor['castImport'];
            }
        }

        // A discriminated schema (Rol, ZaakObject) carries its polymorphic sub-object only on its
        // subtypes, not on the base properties walked above, so inject it from the discriminator.
        $this->appendDiscriminatorField($schemaName, $fields, $casts, $imports);

        // An expandable resource gains a typed _expand sub-object holding its embedded relations.
        $this->appendExpandField($schemaName, $fields, $casts, $imports);

        $contents = $this->renderClass($className, $schemaName, $isRoot, $imports, $fields, $casts);
        $this->files[$this->outDir.'/'.$className.'.php'] = $contents;
    }

    /**
     * If the schema uses a discriminator, append the polymorphic sub-object field (resolved by a
     * sibling discriminator value into a typed sub-DTO) and its DiscriminatorCast, and queue the
     * leaf DTOs for generation.
     *
     * @param  list<string>  $fields
     * @param  array<string, string>  $casts
     * @param  list<string>  $imports
     */
    private function appendDiscriminatorField(string $schemaName, array &$fields, array &$casts, array &$imports): void
    {
        // Presence across releases (for version metadata): the releases whose schema is discriminated.
        $present = [];
        $resolution = null;

        foreach ($this->releaseOrder as $release) {
            $candidate = $this->specsByRelease[$release]->discriminatorResolution($schemaName);
            if ($candidate !== null) {
                $present[] = $release;
                $resolution = $candidate; // Newest wins.
            }
        }

        if ($resolution === null) {
            return;
        }

        $config = $this->discriminators[$schemaName] ?? [];
        $only = $config['only'] ?? null;
        $fallbackToRaw = (bool) ($config['fallbackToRaw'] ?? false);

        $map = [];
        $leafImports = [];

        foreach ($resolution['map'] as $value => $leaf) {
            if ($only !== null && ! in_array($value, $only, true)) {
                continue;
            }

            $map[$value] = $leaf;
            $this->objectQueue[$leaf] ??= false;
            $leafImports[] = $this->namespace.'\\'.$leaf;
        }

        if ($map === []) {
            return;
        }

        $field = $resolution['field'];
        $since = $present[0] === $this->releaseOrder[0] ? null : $present[0];
        $removedIn = $this->removedIn($present);

        $unionDoc = implode('|', array_values(array_unique(array_values($map))));
        if ($fallbackToRaw) {
            $unionDoc .= '|array<string, mixed>';
        }
        $descriptor = [
            'php' => $fallbackToRaw ? 'mixed' : '?Data',
            'doc' => "@var {$unionDoc}|null",
            'cast' => null,
            'castImport' => null,
            'imports' => [],
        ];

        $fields[] = $this->renderField($field, $descriptor, $since, $removedIn);

        $entries = [];
        foreach ($map as $value => $leaf) {
            $entries[] = var_export($value, true).' => '.$leaf.'::class';
        }
        $castArgs = var_export($resolution['property'], true).', ['.implode(', ', $entries).']';
        if ($fallbackToRaw) {
            $castArgs .= ', true';
        }
        $casts[$field] = "new DiscriminatorCast({$castArgs})";

        $imports[] = 'Woweb\Zgw\Data\Casts\DiscriminatorCast';
        if (! $fallbackToRaw) {
            $imports[] = 'Woweb\Zgw\Data\Data';
        }
        foreach ($leafImports as $import) {
            $imports[] = $import;
        }
    }

    /**
     * If the schema has an expanded variant ({Schema}Expanded), append the typed _expand field that
     * carries its embedded related resources, and queue the embedded schema for generation. The
     * field is null on a response that was not expanded.
     *
     * @param  list<string>  $fields
     * @param  array<string, string>  $casts
     * @param  list<string>  $imports
     */
    private function appendExpandField(string $schemaName, array &$fields, array &$casts, array &$imports): void
    {
        $present = [];
        $embedded = null;

        foreach ($this->releaseOrder as $release) {
            $candidate = $this->specsByRelease[$release]->expandResolution($schemaName);
            if ($candidate !== null) {
                $present[] = $release;
                $embedded = $candidate; // Newest wins.
            }
        }

        if ($embedded === null) {
            return;
        }

        $this->objectQueue[$embedded] ??= false;

        $since = $present[0] === $this->releaseOrder[0] ? null : $present[0];
        $removedIn = $this->removedIn($present);

        $descriptor = [
            'php' => '?'.$embedded,
            'doc' => null,
            'cast' => "new DtoCast({$embedded}::class)",
            'castImport' => 'Woweb\Zgw\Data\Casts\DtoCast',
            'imports' => ['Woweb\Zgw\Data\Casts\DtoCast'],
        ];

        $fields[] = $this->renderField('_expand', $descriptor, $since, $removedIn);
        $casts['_expand'] = $descriptor['cast'];
        $imports[] = $descriptor['castImport'];
    }

    /**
     * Resolve a property's reference to a typed DTO that lives outside the plain "object with a
     * properties map" case: a cross-component external $ref (an expanded zaak's `zaaktype` points at
     * the catalogi ZaakType) or a same-component {Schema}Expanded reference (which maps to that
     * resource's base DTO, since the base DTO already carries its own _expand).
     *
     * Returns a link descriptor (the PHP type reference, the `::class` expression and any imports),
     * `['raw' => true]` when a reference is present but cannot be resolved to a generated DTO (so the
     * field degrades to a raw array), or null when the property is not such a reference and the
     * normal describe path applies.
     *
     * @param  array<string, mixed>  $propSchema
     * @return array{typeRef: string, classExpr: string, imports: list<string>}|array{raw: true}|null
     */
    private function linkedRef(array $propSchema): ?array
    {
        foreach ($this->candidateRefs($propSchema) as $ref) {
            // Cross-component external reference (a file path before the fragment).
            if (! str_starts_with($ref, '#/')) {
                return $this->crossComponentTarget($ref) ?? ['raw' => true];
            }

            // Same-component expanded reference: link to the base resource's DTO.
            $name = $this->refName($ref);
            if (str_ends_with($name, 'Expanded')) {
                $base = substr($name, 0, -strlen('Expanded'));

                if (in_array($base, $this->rootSchemas, true)) {
                    return ['typeRef' => $base.'Data', 'classExpr' => $base.'Data', 'imports' => []];
                }

                return ['raw' => true];
            }
        }

        return null;
    }

    /**
     * The DTO an external cross-component $ref points at, or null when the target component is not
     * generated or the schema is not one of its root resources.
     *
     * @return array{typeRef: string, classExpr: string, imports: list<string>}|null
     */
    private function crossComponentTarget(string $ref): ?array
    {
        $path = explode('#', $ref)[0];
        $component = null;

        foreach (explode('/', $path) as $segment) {
            if ($segment !== '' && isset($this->rootSchemasByComponent[$segment])) {
                $component = $segment;
                break;
            }
        }

        if ($component === null) {
            return null;
        }

        $schema = $this->refName($ref);

        if (! in_array($schema, $this->rootSchemasByComponent[$component], true)) {
            return null;
        }

        // A leading-backslash FQN avoids importing across namespaces and any short-name collisions.
        $fqn = '\\'.$this->baseNamespace.'\\'.EndpointResources::componentNamespace($component).'\\'.$schema.'Data';

        return ['typeRef' => $fqn, 'classExpr' => $fqn, 'imports' => []];
    }

    /**
     * The generated class name for a same-component object reference, queueing it when it is not
     * already a root. A root resource is generated as {Schema}Data (and is already queued), so a
     * nested reference to it must use that name rather than the bare schema name.
     */
    private function objectClass(string $refName): string
    {
        if (in_array($refName, $this->rootSchemas, true)) {
            return $refName.'Data';
        }

        $this->objectQueue[$refName] ??= false;

        return $refName;
    }

    /**
     * The reference strings a property offers, from a direct $ref or the members of a
     * oneOf/anyOf/allOf, skipping the tolerant-fallback placeholders.
     *
     * @param  array<string, mixed>  $schema
     * @return list<string>
     */
    private function candidateRefs(array $schema): array
    {
        $refs = [];

        if (isset($schema['$ref']) && is_string($schema['$ref'])) {
            $refs[] = $schema['$ref'];
        }

        foreach (['oneOf', 'anyOf', 'allOf'] as $combiner) {
            if (! isset($schema[$combiner]) || ! is_array($schema[$combiner])) {
                continue;
            }

            foreach ($schema[$combiner] as $member) {
                if (! is_array($member) || ! isset($member['$ref']) || ! is_string($member['$ref'])) {
                    continue;
                }

                if (in_array($this->refName($member['$ref']), ['BlankEnum', 'NullEnum', 'GenesteExpansie', 'EmptyObject'], true)) {
                    continue;
                }

                $refs[] = $member['$ref'];
            }
        }

        return $refs;
    }

    /**
     * @param  array{typeRef: string, classExpr: string, imports: list<string>}  $linked
     * @return array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}
     */
    private function linkedScalarDescriptor(array $linked): array
    {
        return [
            'php' => '?'.$linked['typeRef'],
            'doc' => null,
            'cast' => "new DtoCast({$linked['classExpr']}::class)",
            'castImport' => 'Woweb\Zgw\Data\Casts\DtoCast',
            'imports' => array_merge(['Woweb\Zgw\Data\Casts\DtoCast'], $linked['imports']),
        ];
    }

    /**
     * @param  array{typeRef: string, classExpr: string, imports: list<string>}  $linked
     * @return array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}
     */
    private function linkedCollectionDescriptor(array $linked): array
    {
        return [
            'php' => '?array',
            'doc' => "@var list<{$linked['typeRef']}>|null",
            'cast' => "new DtoCollectionCast({$linked['classExpr']}::class)",
            'castImport' => 'Woweb\Zgw\Data\Casts\DtoCollectionCast',
            'imports' => array_merge(['Woweb\Zgw\Data\Casts\DtoCollectionCast'], $linked['imports']),
        ];
    }

    /**
     * @return array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}
     */
    private function rawDescriptor(): array
    {
        return [
            'php' => '?array',
            'doc' => '@var array<string, mixed>|null Kept as a raw structure.',
            'cast' => null,
            'castImport' => null,
            'imports' => [],
        ];
    }

    /**
     * The first release in which a field is no longer present (it existed earlier and was removed),
     * or null when the field still exists in the newest release.
     *
     * @param  list<string>  $present  Releases in which the field appears, oldest first.
     */
    private function removedIn(array $present): ?string
    {
        $lastPresent = $present[count($present) - 1];
        $index = array_search($lastPresent, $this->releaseOrder, true);

        if ($index === false || $index === count($this->releaseOrder) - 1) {
            return null;
        }

        return $this->releaseOrder[$index + 1];
    }

    /**
     * Resolve a property schema into a field descriptor.
     *
     * @param  array<string, mixed>  $propSchema
     * @return array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}
     */
    private function describe(array $propSchema, SpecModel $spec): array
    {
        // Cross-component external $ref or a same-component {Schema}Expanded reference resolves to a
        // DTO outside the plain object-with-properties case, or degrades to a raw array.
        $linked = $this->linkedRef($propSchema);
        if ($linked !== null) {
            return isset($linked['raw']) ? $this->rawDescriptor() : $this->linkedScalarDescriptor($linked);
        }

        [$resolved, $refName] = $this->unwrap($propSchema, $spec);

        // Value object reference: a stable, standardised structure modelled as a hand-written value
        // object (for example GeoJSON). Handled first because such schemas are polymorphic and need
        // not have a flat "properties" map.
        if ($refName !== null && isset($this->valueObjects[$refName])) {
            $type = $this->valueObjects[$refName]['type'];
            $cast = $this->valueObjects[$refName]['cast'];

            return [
                'php' => '?'.$this->shortName($type),
                'doc' => null,
                'cast' => 'new '.$this->shortName($cast),
                'castImport' => $cast,
                'imports' => [$cast, $type],
            ];
        }

        // Opaque reference: a schema we deliberately keep as a raw structure. Handled before the
        // object branch because such schemas need not have a flat "properties" map.
        if ($refName !== null && in_array($refName, $this->opaque, true)) {
            return [
                'php' => '?array',
                'doc' => '@var array<string, mixed>|null Kept as a raw structure.',
                'cast' => null,
                'castImport' => null,
                'imports' => [],
            ];
        }

        // Enum reference.
        if ($refName !== null && isset($resolved['enum']) && ! in_array($refName, ['BlankEnum', 'NullEnum'], true)) {
            $enumName = $this->enumClass($refName);
            $this->enumQueue[$refName] = true;

            return [
                'php' => '?'.$enumName,
                'doc' => null,
                'cast' => "new EnumCast({$enumName}::class)",
                'castImport' => 'Woweb\Zgw\Data\Casts\EnumCast',
                'imports' => ['Woweb\Zgw\Data\Casts\EnumCast', $this->namespace.'\\Enums\\'.$enumName],
            ];
        }

        // Object reference.
        if ($refName !== null && isset($resolved['properties'])) {
            $class = $this->objectClass($refName);

            return [
                'php' => '?'.$class,
                'doc' => null,
                'cast' => "new DtoCast({$class}::class)",
                'castImport' => 'Woweb\Zgw\Data\Casts\DtoCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DtoCast', $this->namespace.'\\'.$class],
            ];
        }

        $type = is_string($resolved['type'] ?? null) ? $resolved['type'] : null;
        $format = is_string($resolved['format'] ?? null) ? $resolved['format'] : null;

        // Arrays.
        if ($type === 'array') {
            return $this->describeArray($resolved, $spec);
        }

        // A typeless object (no properties, no $ref) is kept as a raw array. Typing it ?string would
        // make hydration throw a TypeError the moment an object value arrives.
        if ($type === 'object') {
            return $this->rawDescriptor();
        }

        // Scalars by format.
        if ($format === 'date' || $format === 'date-time') {
            return [
                'php' => '?CarbonImmutable',
                'doc' => null,
                'cast' => 'new DateTimeCast',
                'castImport' => 'Woweb\Zgw\Data\Casts\DateTimeCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DateTimeCast', 'Carbon\CarbonImmutable'],
            ];
        }

        if ($format === 'duration') {
            return [
                'php' => '?CarbonInterval',
                'doc' => null,
                'cast' => 'new DurationCast',
                'castImport' => 'Woweb\Zgw\Data\Casts\DurationCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DurationCast', 'Carbon\CarbonInterval'],
            ];
        }

        if ($format === 'uri') {
            return [
                'php' => '?Reference',
                'doc' => null,
                'cast' => 'new ReferenceCast',
                'castImport' => 'Woweb\Zgw\Data\Casts\ReferenceCast',
                'imports' => ['Woweb\Zgw\Data\Casts\ReferenceCast', 'Woweb\Zgw\Data\Values\Reference'],
            ];
        }

        return [
            'php' => '?'.$this->scalarType($type),
            'doc' => null,
            'cast' => null,
            'castImport' => null,
            'imports' => [],
        ];
    }

    /**
     * @param  array<string, mixed>  $resolved
     * @return array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}
     */
    private function describeArray(array $resolved, SpecModel $spec): array
    {
        $items = is_array($resolved['items'] ?? null) ? $resolved['items'] : [];

        // A list of cross-component or expanded references (an expanded zaak's `deelzaken` is a list
        // of ZaakExpanded, its `rollen` a list of RolExpanded) links to a list of those DTOs.
        $linked = $this->linkedRef($items);
        if ($linked !== null) {
            return isset($linked['raw']) ? $this->rawDescriptor() : $this->linkedCollectionDescriptor($linked);
        }

        [$itemResolved, $itemRef] = $this->unwrap($items, $spec);

        if ($itemRef !== null && isset($itemResolved['properties']) && ! in_array($itemRef, $this->opaque, true)) {
            $class = $this->objectClass($itemRef);

            return [
                'php' => '?array',
                'doc' => "@var list<{$class}>|null",
                'cast' => "new DtoCollectionCast({$class}::class)",
                'castImport' => 'Woweb\Zgw\Data\Casts\DtoCollectionCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DtoCollectionCast', $this->namespace.'\\'.$class],
            ];
        }

        $itemType = ($itemResolved['type'] ?? null) === 'object'
            ? 'array<string, mixed>'
            : (is_string($itemResolved['type'] ?? null) ? $this->scalarType($itemResolved['type']) : 'string');

        return [
            'php' => '?array',
            'doc' => "@var list<{$itemType}>|null",
            'cast' => null,
            'castImport' => null,
            'imports' => [],
        ];
    }

    /**
     * Unwrap allOf / oneOf / a direct $ref, returning the resolved schema and the referenced
     * schema name (the basename of the $ref) when there is one.
     *
     * @param  array<string, mixed>  $schema
     * @return array{0: array<string, mixed>, 1: ?string}
     */
    private function unwrap(array $schema, SpecModel $spec): array
    {
        if (isset($schema['$ref']) && is_string($schema['$ref'])) {
            $resolved = $spec->resolve($schema['$ref']) ?? [];

            return [$resolved, $this->refName($schema['$ref'])];
        }

        foreach (['allOf', 'oneOf', 'anyOf'] as $combiner) {
            if (! isset($schema[$combiner]) || ! is_array($schema[$combiner])) {
                continue;
            }

            foreach ($schema[$combiner] as $member) {
                if (! is_array($member) || ! isset($member['$ref']) || ! is_string($member['$ref'])) {
                    continue;
                }

                $name = $this->refName($member['$ref']);
                if (in_array($name, ['BlankEnum', 'NullEnum'], true)) {
                    continue;
                }

                return [$spec->resolve($member['$ref']) ?? [], $name];
            }
        }

        return [$schema, null];
    }

    /**
     * Property names of a schema, resolving allOf and a top-level $ref, in declaration order.
     *
     * @param  array<string, mixed>  $schema
     * @return array<string, array<string, mixed>>
     */
    private function mergedProperties(SpecModel $spec, array $schema, int $depth = 0): array
    {
        if ($depth > 12) {
            return [];
        }

        if (isset($schema['$ref']) && is_string($schema['$ref'])) {
            $resolved = $spec->resolve($schema['$ref']);

            return $resolved === null ? [] : $this->mergedProperties($spec, $resolved, $depth + 1);
        }

        $properties = [];

        if (isset($schema['properties']) && is_array($schema['properties'])) {
            foreach ($schema['properties'] as $name => $sub) {
                if (is_array($sub)) {
                    $properties[(string) $name] = $sub;
                }
            }
        }

        if (isset($schema['allOf']) && is_array($schema['allOf'])) {
            foreach ($schema['allOf'] as $member) {
                if (is_array($member)) {
                    $properties += $this->mergedProperties($spec, $member, $depth + 1);
                }
            }
        }

        return $properties;
    }

    private function refName(string $ref): string
    {
        $parts = explode('/', $ref);

        return (string) end($parts);
    }

    private function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);

        return (string) end($parts);
    }

    private function enumClass(string $refName): string
    {
        return Str::studly(preg_replace('/Enum$/', '', $refName) ?? $refName);
    }

    private function scalarType(?string $type): string
    {
        return match ($type) {
            'integer' => 'int',
            'number' => 'float',
            'boolean' => 'bool',
            default => 'string',
        };
    }

    /**
     * @param  array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}  $descriptor
     */
    private function renderField(string $field, array $descriptor, ?string $since, ?string $removedIn): string
    {
        $docLines = [];
        if ($descriptor['doc'] !== null) {
            $docLines[] = $descriptor['doc'];
        }
        if ($since !== null) {
            $docLines[] = "@since ZGW {$since}";
        }
        if ($removedIn !== null) {
            $docLines[] = "@deprecated Removed in ZGW {$removedIn}";
        }

        $out = '';
        if ($docLines !== []) {
            $out .= '    /** '.implode(' ', $docLines)." */\n";
        }
        $out .= "    public {$descriptor['php']} \${$field};";

        return $out;
    }

    /**
     * @param  list<string>  $imports
     * @param  list<string>  $fields
     * @param  array<string, string>  $casts
     */
    private function renderClass(string $className, string $schemaName, bool $isRoot, array $imports, array $fields, array $casts): string
    {
        $imports = array_values(array_unique($imports));
        sort($imports);
        $useBlock = implode("\n", array_map(static fn (string $i): string => "use {$i};", $imports));

        $marker = " * @zgw-schema {$this->component}:{$schemaName}";

        $doc = $isRoot
            ? "/**\n * Generated from the ZGW \"{$schemaName}\" schema (component: {$this->component}).\n *\n * Superset of the fields across releases ".implode(', ', $this->releaseOrder).". A field that does not exist in\n * the release a connection targets hydrates to null.\n *\n{$marker}\n */"
            : "/**\n * Generated from the ZGW \"{$schemaName}\" schema (component: {$this->component}).\n *\n{$marker}\n */";

        $body = implode("\n\n", $fields);

        $castsBlock = '';
        if ($casts !== []) {
            $lines = [];
            foreach ($casts as $field => $expr) {
                $lines[] = "            '{$field}' => {$expr},";
            }
            $castsBlock = "\n\n    /**\n     * @return array<string, \\Woweb\\Zgw\\Data\\Casts\\Cast>\n     */\n    protected static function casts(): array\n    {\n        return [\n".implode("\n", $lines)."\n        ];\n    }";
        }

        return "<?php\n\ndeclare(strict_types=1);\n\n".self::HEADER."\n\nnamespace {$this->namespace};\n\n{$useBlock}\n\n{$doc}\nclass {$className} extends Data\n{\n{$body}{$castsBlock}\n}\n";
    }

    /**
     * Turn an enum value into a valid, unique PHP case name. ZGW has enums whose values contain
     * spaces and punctuation (display labels) and values that start with a digit, so the raw value
     * cannot be used as an identifier.
     *
     * @param  array<string, bool>  $seen
     */
    private function enumCaseName(string $value, array &$seen): string
    {
        $name = Str::studly((string) preg_replace('/[^A-Za-z0-9]+/', ' ', $value));

        if ($name === '' || ctype_digit($name[0])) {
            $name = 'Value'.$name;
        }

        $candidate = $name;
        $suffix = 2;
        while (isset($seen[$candidate])) {
            $candidate = $name.$suffix;
            $suffix++;
        }
        $seen[$candidate] = true;

        return $candidate;
    }

    private function generateEnum(string $refName): void
    {
        $schema = $this->latest->componentSchema($refName);
        $values = is_array($schema['enum'] ?? null) ? $schema['enum'] : [];
        $enumName = $this->enumClass($refName);

        $cases = [];
        $seen = [];
        foreach ($values as $value) {
            if (! is_string($value) || $value === '') {
                continue;
            }
            $case = $this->enumCaseName($value, $seen);
            $cases[] = "    case {$case} = ".var_export($value, true).';';
        }

        $body = implode("\n", $cases);

        $contents = "<?php\n\ndeclare(strict_types=1);\n\n".self::HEADER."\n\nnamespace {$this->namespace}\\Enums;\n\nenum {$enumName}: string\n{\n{$body}\n}\n";

        $this->files[$this->outDir.'/Enums/'.$enumName.'.php'] = $contents;
    }
}
