<?php

declare(strict_types=1);

namespace Woweb\Zgw\Dev\Dto;

use Illuminate\Support\Str;
use RuntimeException;
use Woweb\Zgw\Tests\Contract\Support\ReleaseMatrix;
use Woweb\Zgw\Tests\Contract\Support\SpecModel;

/**
 * Generates the typed read DTOs from the pinned ZGW OpenAPI specs.
 *
 * The generator is a require-dev tool: its output (the DTOs, nested value DTOs and enums) is
 * committed, so the runtime never carries the generator. It reads the same spec fixtures the
 * contract suite pins, builds a superset of fields across releases, annotates per-field @since
 * for fields that did not exist in the earliest supported release, and picks a cast per field
 * from the field's type, format, enum or object reference.
 *
 * The "Data" namespace must not depend on anything in this dev namespace; the dependency only
 * runs at generation time.
 */
final class DtoGenerator
{
    private const HEADER = '// This file is generated by `composer dto:generate`. Do not edit it by hand.';

    /** @var array<string, SpecModel> keyed by release label. */
    private array $specsByRelease = [];

    /** @var list<string> release labels sorted oldest first (for example "1.5", "1.6", "1.7"). */
    private array $releaseOrder = [];

    private SpecModel $latest;

    /** @var array<string, bool> object schema name => isRoot, queued for generation. */
    private array $objectQueue = [];

    /** @var array<string, bool> object schema names already generated. */
    private array $objectDone = [];

    /** @var array<string, bool> enum schema names queued. */
    private array $enumQueue = [];

    /** @var array<string, string> written file path => contents. */
    private array $files = [];

    /**
     * @param  string  $component  ZGW component the schema lives in (for example "zaken").
     * @param  string  $rootSchema  Root schema name (for example "Zaak").
     * @param  string  $namespace  Base namespace for generated objects (for example Woweb\Zgw\Data\Generated).
     * @param  string  $outDir  Directory the objects are written to.
     * @param  list<string>  $opaque  Object schema names kept as raw arrays rather than generated DTOs.
     * @param  array<string, array{type: class-string, cast: class-string}>  $valueObjects  Schema
     *                                                                                      names mapped to a hand-written value object and its cast (for stable, standardised
     *                                                                                      structures such as GeoJSON that are modelled as value objects, not generated DTOs).
     */
    public function __construct(
        private readonly string $component,
        private readonly string $rootSchema,
        private readonly string $namespace,
        private readonly string $outDir,
        private readonly array $opaque = [],
        private readonly array $valueObjects = [],
    ) {}

    /**
     * @return list<string> the paths written.
     */
    public function generate(): array
    {
        $this->loadSpecs();

        $this->objectQueue[$this->rootSchema] = true;

        while ($this->objectQueue !== []) {
            $name = array_key_first($this->objectQueue);
            $isRoot = $this->objectQueue[$name];
            unset($this->objectQueue[$name]);

            if (isset($this->objectDone[$name])) {
                continue;
            }

            $this->objectDone[$name] = true;
            $this->generateObject($name, $isRoot);
        }

        foreach (array_keys($this->enumQueue) as $enumSchema) {
            $this->generateEnum($enumSchema);
        }

        $paths = [];

        foreach ($this->files as $path => $contents) {
            $dir = dirname($path);
            if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
                throw new RuntimeException("Could not create directory [{$dir}].");
            }
            file_put_contents($path, $contents);
            $paths[] = $path;
        }

        sort($paths);

        return $paths;
    }

    private function loadSpecs(): void
    {
        foreach (array_keys(ReleaseMatrix::releases()) as $release) {
            $file = ReleaseMatrix::specFile($release, $this->component);
            if ($file === null) {
                continue;
            }
            $this->specsByRelease[$release] = SpecModel::fromFile($file);
            $this->releaseOrder[] = $release;
        }

        if ($this->specsByRelease === []) {
            throw new RuntimeException(
                "No spec fixtures found for component [{$this->component}]. Run `composer contract:fetch` first."
            );
        }

        sort($this->releaseOrder);
        $this->latest = $this->specsByRelease[$this->releaseOrder[count($this->releaseOrder) - 1]];
    }

    private function generateObject(string $schemaName, bool $isRoot): void
    {
        $schema = $this->latest->componentSchema($schemaName);

        if ($schema === null) {
            throw new RuntimeException("Schema [{$schemaName}] not found in the latest {$this->component} spec.");
        }

        $properties = $this->mergedProperties($this->latest, $schema);
        $className = $isRoot ? $schemaName.'Data' : $schemaName;

        $fields = [];
        $casts = [];
        $imports = ['Woweb\Zgw\Data\Data'];

        foreach ($properties as $field => $propSchema) {
            $descriptor = $this->describe($propSchema);
            $since = $this->sinceFor($schemaName, $field);

            $fields[] = $this->renderField($field, $descriptor, $since);

            foreach ($descriptor['imports'] as $import) {
                $imports[] = $import;
            }

            if ($descriptor['cast'] !== null && $descriptor['castImport'] !== null) {
                $casts[$field] = $descriptor['cast'];
                $imports[] = $descriptor['castImport'];
            }
        }

        $contents = $this->renderClass($className, $schemaName, $isRoot, $imports, $fields, $casts);
        $this->files[$this->outDir.'/'.$className.'.php'] = $contents;
    }

    /**
     * Resolve a property schema into a field descriptor.
     *
     * @param  array<string, mixed>  $propSchema
     * @return array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}
     */
    private function describe(array $propSchema): array
    {
        [$resolved, $refName] = $this->unwrap($propSchema);

        // Value object reference: a stable, standardised structure modelled as a hand-written value
        // object (for example GeoJSON). Handled first because such schemas are polymorphic and need
        // not have a flat "properties" map.
        if ($refName !== null && isset($this->valueObjects[$refName])) {
            $type = $this->valueObjects[$refName]['type'];
            $cast = $this->valueObjects[$refName]['cast'];

            return [
                'php' => '?'.$this->shortName($type),
                'doc' => null,
                'cast' => 'new '.$this->shortName($cast),
                'castImport' => $cast,
                'imports' => [$cast, $type],
            ];
        }

        // Opaque reference: a schema we deliberately keep as a raw structure. Handled before the
        // object branch because such schemas need not have a flat "properties" map.
        if ($refName !== null && in_array($refName, $this->opaque, true)) {
            return [
                'php' => '?array',
                'doc' => '@var array<string, mixed>|null Kept as a raw structure.',
                'cast' => null,
                'castImport' => null,
                'imports' => [],
            ];
        }

        // Enum reference.
        if ($refName !== null && isset($resolved['enum']) && ! in_array($refName, ['BlankEnum', 'NullEnum'], true)) {
            $enumName = $this->enumClass($refName);
            $this->enumQueue[$refName] = true;

            return [
                'php' => '?'.$enumName,
                'doc' => null,
                'cast' => "new EnumCast({$enumName}::class)",
                'castImport' => 'Woweb\Zgw\Data\Casts\EnumCast',
                'imports' => ['Woweb\Zgw\Data\Casts\EnumCast', $this->namespace.'\\Enums\\'.$enumName],
            ];
        }

        // Object reference.
        if ($refName !== null && isset($resolved['properties'])) {
            $this->objectQueue[$refName] ??= false;

            return [
                'php' => '?'.$refName,
                'doc' => null,
                'cast' => "new DtoCast({$refName}::class)",
                'castImport' => 'Woweb\Zgw\Data\Casts\DtoCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DtoCast', $this->namespace.'\\'.$refName],
            ];
        }

        $type = is_string($resolved['type'] ?? null) ? $resolved['type'] : null;
        $format = is_string($resolved['format'] ?? null) ? $resolved['format'] : null;

        // Arrays.
        if ($type === 'array') {
            return $this->describeArray($resolved);
        }

        // Scalars by format.
        if ($format === 'date' || $format === 'date-time') {
            return [
                'php' => '?CarbonImmutable',
                'doc' => null,
                'cast' => 'new DateTimeCast',
                'castImport' => 'Woweb\Zgw\Data\Casts\DateTimeCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DateTimeCast', 'Carbon\CarbonImmutable'],
            ];
        }

        if ($format === 'duration') {
            return [
                'php' => '?CarbonInterval',
                'doc' => null,
                'cast' => 'new DurationCast',
                'castImport' => 'Woweb\Zgw\Data\Casts\DurationCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DurationCast', 'Carbon\CarbonInterval'],
            ];
        }

        if ($format === 'uri') {
            return [
                'php' => '?Reference',
                'doc' => null,
                'cast' => 'new ReferenceCast',
                'castImport' => 'Woweb\Zgw\Data\Casts\ReferenceCast',
                'imports' => ['Woweb\Zgw\Data\Casts\ReferenceCast', 'Woweb\Zgw\Data\Values\Reference'],
            ];
        }

        return [
            'php' => '?'.$this->scalarType($type),
            'doc' => null,
            'cast' => null,
            'castImport' => null,
            'imports' => [],
        ];
    }

    /**
     * @param  array<string, mixed>  $resolved
     * @return array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}
     */
    private function describeArray(array $resolved): array
    {
        $items = is_array($resolved['items'] ?? null) ? $resolved['items'] : [];
        [$itemResolved, $itemRef] = $this->unwrap($items);

        if ($itemRef !== null && isset($itemResolved['properties']) && ! in_array($itemRef, $this->opaque, true)) {
            $this->objectQueue[$itemRef] ??= false;

            return [
                'php' => '?array',
                'doc' => "@var list<{$itemRef}>|null",
                'cast' => "new DtoCollectionCast({$itemRef}::class)",
                'castImport' => 'Woweb\Zgw\Data\Casts\DtoCollectionCast',
                'imports' => ['Woweb\Zgw\Data\Casts\DtoCollectionCast', $this->namespace.'\\'.$itemRef],
            ];
        }

        $itemType = is_string($itemResolved['type'] ?? null) ? $this->scalarType($itemResolved['type']) : 'string';

        return [
            'php' => '?array',
            'doc' => "@var list<{$itemType}>|null",
            'cast' => null,
            'castImport' => null,
            'imports' => [],
        ];
    }

    /**
     * Unwrap allOf / oneOf / a direct $ref, returning the resolved schema and the referenced
     * schema name (the basename of the $ref) when there is one.
     *
     * @param  array<string, mixed>  $schema
     * @return array{0: array<string, mixed>, 1: ?string}
     */
    private function unwrap(array $schema): array
    {
        if (isset($schema['$ref']) && is_string($schema['$ref'])) {
            $resolved = $this->latest->resolve($schema['$ref']) ?? [];

            return [$resolved, $this->refName($schema['$ref'])];
        }

        foreach (['allOf', 'oneOf', 'anyOf'] as $combiner) {
            if (! isset($schema[$combiner]) || ! is_array($schema[$combiner])) {
                continue;
            }

            foreach ($schema[$combiner] as $member) {
                if (! is_array($member) || ! isset($member['$ref']) || ! is_string($member['$ref'])) {
                    continue;
                }

                $name = $this->refName($member['$ref']);
                if (in_array($name, ['BlankEnum', 'NullEnum'], true)) {
                    continue;
                }

                return [$this->latest->resolve($member['$ref']) ?? [], $name];
            }
        }

        return [$schema, null];
    }

    /**
     * Property names of a schema, resolving allOf and a top-level $ref, in declaration order.
     *
     * @param  array<string, mixed>  $schema
     * @return array<string, array<string, mixed>>
     */
    private function mergedProperties(SpecModel $spec, array $schema, int $depth = 0): array
    {
        if ($depth > 12) {
            return [];
        }

        if (isset($schema['$ref']) && is_string($schema['$ref'])) {
            $resolved = $spec->resolve($schema['$ref']);

            return $resolved === null ? [] : $this->mergedProperties($spec, $resolved, $depth + 1);
        }

        $properties = [];

        if (isset($schema['properties']) && is_array($schema['properties'])) {
            foreach ($schema['properties'] as $name => $sub) {
                if (is_array($sub)) {
                    $properties[(string) $name] = $sub;
                }
            }
        }

        if (isset($schema['allOf']) && is_array($schema['allOf'])) {
            foreach ($schema['allOf'] as $member) {
                if (is_array($member)) {
                    $properties += $this->mergedProperties($spec, $member, $depth + 1);
                }
            }
        }

        return $properties;
    }

    /**
     * The earliest supported release in which a schema property appears, or null when it exists in
     * the earliest release (and therefore needs no @since annotation).
     */
    private function sinceFor(string $schemaName, string $field): ?string
    {
        foreach ($this->releaseOrder as $release) {
            $schema = $this->specsByRelease[$release]->componentSchema($schemaName);
            if ($schema === null) {
                continue;
            }

            $present = array_key_exists($field, $this->mergedProperties($this->specsByRelease[$release], $schema));

            if ($present) {
                return $release === $this->releaseOrder[0] ? null : $release;
            }
        }

        return null;
    }

    private function refName(string $ref): string
    {
        $parts = explode('/', $ref);

        return (string) end($parts);
    }

    private function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);

        return (string) end($parts);
    }

    private function enumClass(string $refName): string
    {
        return Str::studly(preg_replace('/Enum$/', '', $refName) ?? $refName);
    }

    private function scalarType(?string $type): string
    {
        return match ($type) {
            'integer' => 'int',
            'number' => 'float',
            'boolean' => 'bool',
            default => 'string',
        };
    }

    /**
     * @param  array{php: string, doc: ?string, cast: ?string, castImport: ?string, imports: list<string>}  $descriptor
     */
    private function renderField(string $field, array $descriptor, ?string $since): string
    {
        $docLines = [];
        if ($descriptor['doc'] !== null) {
            $docLines[] = $descriptor['doc'];
        }
        if ($since !== null) {
            $docLines[] = "@since ZGW {$since}";
        }

        $out = '';
        if ($docLines !== []) {
            $out .= '    /** '.implode(' ', $docLines)." */\n";
        }
        $out .= "    public {$descriptor['php']} \${$field};";

        return $out;
    }

    /**
     * @param  list<string>  $imports
     * @param  list<string>  $fields
     * @param  array<string, string>  $casts
     */
    private function renderClass(string $className, string $schemaName, bool $isRoot, array $imports, array $fields, array $casts): string
    {
        $imports = array_values(array_unique($imports));
        sort($imports);
        $useBlock = implode("\n", array_map(static fn (string $i): string => "use {$i};", $imports));

        $doc = $isRoot
            ? "/**\n * Generated from the ZGW \"{$schemaName}\" schema (component: {$this->component}).\n *\n * Superset of the fields across releases ".implode(', ', $this->releaseOrder).". A field that does not exist in\n * the release a connection targets hydrates to null.\n */"
            : "/**\n * Generated from the ZGW \"{$schemaName}\" schema (component: {$this->component}).\n */";

        $body = implode("\n\n", $fields);

        $castsBlock = '';
        if ($casts !== []) {
            $lines = [];
            foreach ($casts as $field => $expr) {
                $lines[] = "            '{$field}' => {$expr},";
            }
            $castsBlock = "\n\n    /**\n     * @return array<string, \\Woweb\\Zgw\\Data\\Casts\\Cast>\n     */\n    protected static function casts(): array\n    {\n        return [\n".implode("\n", $lines)."\n        ];\n    }";
        }

        return "<?php\n\ndeclare(strict_types=1);\n\n".self::HEADER."\n\nnamespace {$this->namespace};\n\n{$useBlock}\n\n{$doc}\nclass {$className} extends Data\n{\n{$body}{$castsBlock}\n}\n";
    }

    private function generateEnum(string $refName): void
    {
        $schema = $this->latest->componentSchema($refName);
        $values = is_array($schema['enum'] ?? null) ? $schema['enum'] : [];
        $enumName = $this->enumClass($refName);

        $cases = [];
        foreach ($values as $value) {
            if (! is_string($value) || $value === '') {
                continue;
            }
            $case = Str::studly($value);
            $cases[] = "    case {$case} = '{$value}';";
        }

        $body = implode("\n", $cases);

        $contents = "<?php\n\ndeclare(strict_types=1);\n\n".self::HEADER."\n\nnamespace {$this->namespace}\\Enums;\n\nenum {$enumName}: string\n{\n{$body}\n}\n";

        $this->files[$this->outDir.'/Enums/'.$enumName.'.php'] = $contents;
    }
}
