<?php

declare(strict_types=1);

namespace Woweb\Zgw\Dev\Dto;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use RuntimeException;
use Woweb\Zgw\Data\Attributes\ZgwResource;

/**
 * Generates the endpoint to DTO map (TypedMap) by reflecting every endpoint for the #[ZgwResource]
 * attribute. The map is generated rather than hand-maintained so it cannot drift from the DTOs.
 */
final class TypedMapGenerator
{
    /**
     * @param  string  $endpointsDir  Directory holding the endpoint classes.
     * @param  string  $endpointNamespace  Base namespace of those endpoints.
     * @param  string  $dtoNamespace  Namespace the generated DTOs live in.
     * @param  string  $outFile  Path of the TypedMap file to write.
     */
    public function __construct(
        private readonly string $endpointsDir,
        private readonly string $endpointNamespace,
        private readonly string $dtoNamespace,
        private readonly string $outFile,
    ) {}

    public function generate(): string
    {
        $map = [];

        foreach ($this->endpointClasses() as $class) {
            $reflection = new ReflectionClass($class);
            $attributes = $reflection->getAttributes(ZgwResource::class);

            if ($attributes === []) {
                continue;
            }

            $resource = $attributes[0]->newInstance();
            $map[$class] = $this->dtoNamespace.'\\'.$resource->schema.'Data';
        }

        ksort($map);

        $lines = [];
        foreach ($map as $endpoint => $dto) {
            $lines[] = "        \\{$endpoint}::class => \\{$dto}::class,";
        }
        $body = implode("\n", $lines);

        $contents = "<?php\n\ndeclare(strict_types=1);\n\n".
            "// This file is generated by `composer dto:generate`. Do not edit it by hand.\n\n".
            "namespace {$this->dtoNamespace};\n\n".
            "/**\n * Maps a kernel endpoint class to the DTO that hydrates its responses.\n */\n".
            "final class TypedMap\n{\n".
            "    /**\n     * @var array<class-string, class-string<\\Woweb\\Zgw\\Data\\Data>>\n     */\n".
            "    public const MAP = [\n{$body}\n    ];\n}\n";

        $dir = dirname($this->outFile);
        if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
            throw new RuntimeException("Could not create directory [{$dir}].");
        }

        file_put_contents($this->outFile, $contents);

        return $this->outFile;
    }

    /**
     * @return list<class-string>
     */
    private function endpointClasses(): array
    {
        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($this->endpointsDir));
        $classes = [];

        foreach ($iterator as $file) {
            if (! $file instanceof \SplFileInfo || $file->getExtension() !== 'php') {
                continue;
            }

            $relative = substr($file->getPathname(), strlen($this->endpointsDir) + 1, -4);
            $class = $this->endpointNamespace.'\\'.str_replace('/', '\\', $relative);

            if (class_exists($class)) {
                /** @var class-string $class */
                $classes[] = $class;
            }
        }

        return $classes;
    }
}
