<?php

declare(strict_types=1);

namespace Woweb\Zgw\Dev\Dto;

use RuntimeException;

/**
 * Generates the endpoint to DTO map (TypedMap) from the #[ZgwResource] attributes on the endpoints.
 * The map is generated rather than hand-maintained so it cannot drift from the DTOs.
 */
final class TypedMapGenerator
{
    /**
     * @param  string  $endpointsDir  Directory holding the endpoint classes.
     * @param  string  $endpointNamespace  Base namespace of those endpoints.
     * @param  string  $dtoNamespace  Base namespace the generated DTOs live in (component sub-namespaces below it).
     * @param  string  $outFile  Path of the TypedMap file to write.
     */
    public function __construct(
        private readonly string $endpointsDir,
        private readonly string $endpointNamespace,
        private readonly string $dtoNamespace,
        private readonly string $outFile,
    ) {}

    public function generate(): string
    {
        $map = [];

        foreach (EndpointResources::discover($this->endpointsDir, $this->endpointNamespace) as $endpoint => $resource) {
            $map[$endpoint] = EndpointResources::dtoClass($this->dtoNamespace, $resource);
        }

        $lines = [];
        foreach ($map as $endpoint => $dto) {
            $lines[] = "        \\{$endpoint}::class => \\{$dto}::class,";
        }
        $body = implode("\n", $lines);

        $contents = "<?php\n\ndeclare(strict_types=1);\n\n".
            "// This file is generated by `composer dto:generate`. Do not edit it by hand.\n\n".
            "namespace {$this->dtoNamespace};\n\n".
            "/**\n * Maps a kernel endpoint class to the DTO that hydrates its responses.\n */\n".
            "final class TypedMap\n{\n".
            "    /**\n     * @var array<class-string, class-string<\\Woweb\\Zgw\\Data\\Data>>\n     */\n".
            "    public const MAP = [\n{$body}\n    ];\n}\n";

        $dir = dirname($this->outFile);
        if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
            throw new RuntimeException("Could not create directory [{$dir}].");
        }

        file_put_contents($this->outFile, $contents);

        return $this->outFile;
    }
}
