<?php

declare(strict_types=1);

namespace Woweb\Zgw\Dev\Dto;

use Illuminate\Support\Str;
use RuntimeException;
use Woweb\Zgw\Tests\Contract\Support\ReleaseMatrix;
use Woweb\Zgw\Tests\Contract\Support\SpecModel;

/**
 * Generates the typed write builders from the pinned ZGW OpenAPI specs.
 *
 * A write builder is the create/update counterpart of a read DTO: one typed setter per writable
 * (not readOnly) field of the resource, each appending to the payload only when called, so a PATCH
 * never emits a field the caller did not touch. Like the read DTOs the output is committed, so the
 * runtime never carries the generator. The builders share the WriteBuilder base, which normalises
 * references, dates and enums.
 *
 * Writable fields are the union across releases of the resource schema's properties that are not
 * readOnly, mirroring how the read DTOs are a superset across releases.
 */
final class WriteBuilderGenerator
{
    private const HEADER = '// This file is generated by `composer dto:generate`. Do not edit it by hand.';

    /** @var array<string, SpecModel> keyed by release label. */
    private array $specsByRelease = [];

    /** @var list<string> release labels sorted oldest first. */
    private array $releaseOrder = [];

    /**
     * @param  string  $component  ZGW component the schemas live in (for example "zaken").
     * @param  list<string>  $rootSchemas  Write-capable root resource schema names for this component.
     * @param  string  $namespace  Namespace for the generated write builders of this component.
     * @param  string  $outDir  Directory the builders are written to.
     * @param  string  $enumNamespace  Namespace the generated read enums live in (reused by setters).
     */
    public function __construct(
        private readonly string $component,
        private readonly array $rootSchemas,
        private readonly string $namespace,
        private readonly string $outDir,
        private readonly string $enumNamespace,
    ) {}

    /**
     * @return list<string> the paths written.
     */
    public function generate(): array
    {
        $this->loadSpecs();

        $paths = [];

        foreach ($this->rootSchemas as $schema) {
            $path = $this->outDir.'/'.$schema.'Write.php';
            file_put_contents($path, $this->generateBuilder($schema));
            $paths[] = $path;
        }

        sort($paths);

        return $paths;
    }

    private function loadSpecs(): void
    {
        foreach (array_keys(ReleaseMatrix::releases()) as $release) {
            $file = ReleaseMatrix::specFile($release, $this->component);
            if ($file === null) {
                continue;
            }
            $this->specsByRelease[$release] = SpecModel::fromFile($file);
            $this->releaseOrder[] = $release;
        }

        if ($this->specsByRelease === []) {
            throw new RuntimeException(
                "No spec fixtures found for component [{$this->component}]. Run `composer contract:fetch` first."
            );
        }

        sort($this->releaseOrder);

        if (! is_dir($this->outDir) && ! mkdir($this->outDir, 0775, true) && ! is_dir($this->outDir)) {
            throw new RuntimeException("Could not create directory [{$this->outDir}].");
        }
    }

    private function generateBuilder(string $schemaName): string
    {
        // Writable properties per release, so the builder is a superset across releases (a field
        // writable in any supported release gets a setter).
        $writable = [];
        foreach ($this->releaseOrder as $release) {
            $schema = $this->specsByRelease[$release]->componentSchema($schemaName);
            if ($schema === null) {
                continue;
            }
            foreach ($this->writableProperties($this->specsByRelease[$release], $schema) as $name => $prop) {
                $writable[$release][$name] = $prop;
            }
        }

        if ($writable === []) {
            throw new RuntimeException("Schema [{$schemaName}] not found in any {$this->component} spec.");
        }

        // Union of field names, newest release first.
        $order = [];
        foreach (array_reverse($this->releaseOrder) as $release) {
            foreach (array_keys($writable[$release] ?? []) as $field) {
                if (! in_array($field, $order, true)) {
                    $order[] = $field;
                }
            }
        }

        $methods = [];
        $imports = [];

        foreach ($order as $field) {
            $sourceRelease = null;
            foreach ($this->releaseOrder as $release) {
                if (isset($writable[$release][$field])) {
                    $sourceRelease = $release; // Newest defining release wins.
                }
            }

            $descriptor = $this->describeWrite($writable[$sourceRelease][$field], $this->specsByRelease[$sourceRelease]);
            $methods[] = $this->renderSetter($field, $descriptor);

            foreach ($descriptor['imports'] as $import) {
                $imports[] = $import;
            }
        }

        return $this->renderClass($schemaName, $imports, $methods);
    }

    /**
     * The schema's writable properties (not readOnly), resolving allOf and a top-level $ref.
     *
     * @param  array<string, mixed>  $schema
     * @return array<string, array<string, mixed>>
     */
    private function writableProperties(SpecModel $spec, array $schema, int $depth = 0): array
    {
        if ($depth > 12) {
            return [];
        }

        if (isset($schema['$ref']) && is_string($schema['$ref'])) {
            $resolved = $spec->resolve($schema['$ref']);

            return $resolved === null ? [] : $this->writableProperties($spec, $resolved, $depth + 1);
        }

        $properties = [];

        if (isset($schema['properties']) && is_array($schema['properties'])) {
            foreach ($schema['properties'] as $name => $sub) {
                if (is_array($sub) && ($sub['readOnly'] ?? false) !== true) {
                    $properties[(string) $name] = $sub;
                }
            }
        }

        if (isset($schema['allOf']) && is_array($schema['allOf'])) {
            foreach ($schema['allOf'] as $member) {
                if (is_array($member)) {
                    $properties += $this->writableProperties($spec, $member, $depth + 1);
                }
            }
        }

        return $properties;
    }

    /**
     * The setter signature and normalisation for a writable property.
     *
     * @param  array<string, mixed>  $propSchema
     * @return array{param: string, expr: string, imports: list<string>}
     */
    private function describeWrite(array $propSchema, SpecModel $spec): array
    {
        [$resolved, $refName] = $this->unwrap($propSchema, $spec);

        // Enum: accept the enum or its scalar, normalise to the backing value.
        if ($refName !== null && isset($resolved['enum']) && ! in_array($refName, ['BlankEnum', 'NullEnum'], true)) {
            $enum = Str::studly(preg_replace('/Enum$/', '', $refName) ?? $refName);

            return [
                'param' => "{$enum}|string|int|null",
                'expr' => '$this->enum($value)',
                'imports' => [$this->enumNamespace.'\\'.$enum],
            ];
        }

        $type = is_string($resolved['type'] ?? null) ? $resolved['type'] : null;
        $format = is_string($resolved['format'] ?? null) ? $resolved['format'] : null;

        if ($format === 'uri') {
            return ['param' => 'Reference|string|null', 'expr' => '$this->reference($value)', 'imports' => ['Woweb\Zgw\Data\Values\Reference']];
        }

        if ($format === 'date') {
            return ['param' => 'DateTimeInterface|string|null', 'expr' => '$this->date($value)', 'imports' => ['DateTimeInterface']];
        }

        if ($format === 'date-time') {
            return ['param' => 'DateTimeInterface|string|null', 'expr' => '$this->dateTime($value)', 'imports' => ['DateTimeInterface']];
        }

        return match ($type) {
            'boolean' => ['param' => '?bool', 'expr' => '$value', 'imports' => []],
            'integer' => ['param' => '?int', 'expr' => '$value', 'imports' => []],
            'number' => ['param' => '?float', 'expr' => '$value', 'imports' => []],
            // Arrays and (nested or typeless) objects are passed through as a raw payload value.
            'array', 'object' => ['param' => '?array', 'expr' => '$value', 'imports' => []],
            default => $refName !== null && isset($resolved['properties'])
                ? ['param' => '?array', 'expr' => '$value', 'imports' => []]
                : ['param' => '?string', 'expr' => '$value', 'imports' => []],
        };
    }

    /**
     * Unwrap allOf / oneOf / a direct $ref, returning the resolved schema and the referenced schema
     * name when there is one.
     *
     * @param  array<string, mixed>  $schema
     * @return array{0: array<string, mixed>, 1: ?string}
     */
    private function unwrap(array $schema, SpecModel $spec): array
    {
        if (isset($schema['$ref']) && is_string($schema['$ref'])) {
            return [$spec->resolve($schema['$ref']) ?? [], $this->refName($schema['$ref'])];
        }

        foreach (['allOf', 'oneOf', 'anyOf'] as $combiner) {
            if (! isset($schema[$combiner]) || ! is_array($schema[$combiner])) {
                continue;
            }

            foreach ($schema[$combiner] as $member) {
                if (! is_array($member) || ! isset($member['$ref']) || ! is_string($member['$ref'])) {
                    continue;
                }

                $name = $this->refName($member['$ref']);
                if (in_array($name, ['BlankEnum', 'NullEnum'], true)) {
                    continue;
                }

                return [$spec->resolve($member['$ref']) ?? [], $name];
            }
        }

        return [$schema, null];
    }

    /**
     * @param  array{param: string, expr: string, imports: list<string>}  $descriptor
     */
    private function renderSetter(string $field, array $descriptor): string
    {
        // An array setter carries a freeform nested payload, so document its value type for the
        // static analyser (level 8 requires iterables to specify their value type).
        $doc = $descriptor['param'] === '?array'
            ? "    /**\n     * @param  array<array-key, mixed>|null  \$value\n     */\n"
            : '';

        return $doc.
            "    public function {$field}({$descriptor['param']} \$value): static\n".
            "    {\n".
            "        return \$this->set('{$field}', {$descriptor['expr']});\n".
            '    }';
    }

    /**
     * @param  list<string>  $imports
     * @param  list<string>  $methods
     */
    private function renderClass(string $schemaName, array $imports, array $methods): string
    {
        $imports[] = 'Woweb\Zgw\Data\Writes\WriteBuilder';
        $imports = array_values(array_unique($imports));
        sort($imports);
        $useBlock = implode("\n", array_map(static fn (string $i): string => "use {$i};", $imports));

        $body = implode("\n\n", $methods);

        $doc = "/**\n * Builds a create or update payload for a {$schemaName}.\n *\n".
            " * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set\n".
            " * just the fields you want to change) and for a create. Set a field to null to clear it on a\n".
            ' * PATCH. Setters carry the writable (not readOnly) fields across releases '.implode(', ', $this->releaseOrder).".\n *\n".
            " * @zgw-write {$this->component}:{$schemaName}\n */";

        return "<?php\n\ndeclare(strict_types=1);\n\n".self::HEADER."\n\nnamespace {$this->namespace};\n\n{$useBlock}\n\n{$doc}\nfinal class {$schemaName}Write extends WriteBuilder\n{\n{$body}\n}\n";
    }

    private function refName(string $ref): string
    {
        $parts = explode('/', $ref);

        return (string) end($parts);
    }
}
