<?php

declare(strict_types=1);

namespace Woweb\Zgw\Tests\Contract;

use PHPUnit\Framework\Attributes\DataProvider;
use Woweb\Zgw\Tests\Contract\Support\OperationRegistry;
use Woweb\Zgw\Tests\Contract\Support\ReleaseMatrix;

/**
 * Informational (non-failing) report of how much of each ZGW release's API surface this package
 * covers. For every release it writes build/zgw-coverage-{release}.md listing the spec operations
 * the client does not implement, including the components it does not support at all (Notificaties
 * and Autorisaties). Use it to track future work, not as a pass/fail gate.
 */
final class CoverageReportTest extends ContractTestCase
{
    /** Core ZGW components that this package does not implement at all. */
    private const UNIMPLEMENTED_COMPONENTS = [];

    /**
     * @return iterable<string, array{0: string}>
     */
    public static function releaseProvider(): iterable
    {
        foreach (array_keys(ReleaseMatrix::releases()) as $release) {
            yield "ZGW {$release}" => [$release];
        }
    }

    #[DataProvider('releaseProvider')]
    public function test_writes_coverage_report(string $release): void
    {
        $components = ReleaseMatrix::releases()[$release]['components'];
        $registry = $this->registryByComponent();

        $lines = [
            "# ZGW {$release} coverage report",
            '',
            'Spec operations not implemented by this package. Generated by the contract test suite.',
            '',
        ];

        $totalSpecOps = 0;
        $totalCovered = 0;

        foreach ($components as $component => $meta) {
            $specFile = ReleaseMatrix::specFile($release, $component);

            if ($specFile === null) {
                continue;
            }

            $spec = $this->loadSpec($release, $component);
            $covered = $registry[$component] ?? [];

            $uncovered = [];
            $specOpCount = 0;

            foreach ($spec->operations() as $operation) {
                // Only count operations the client could meaningfully implement; HEAD/OPTIONS/TRACE
                // mirror GET metadata and are never issued by this package.
                if (! in_array(strtolower($operation['method']), ['get', 'post', 'put', 'patch', 'delete'], true)) {
                    continue;
                }

                $specOpCount++;
                $signature = strtolower($operation['method']).' '.$this->normalize($operation['path']);

                if (in_array($signature, $covered, true)) {
                    $totalCovered++;
                } else {
                    $uncovered[] = strtoupper($operation['method']).' '.$operation['path'];
                }
            }

            $totalSpecOps += $specOpCount;
            $implemented = $specOpCount - count($uncovered);

            $lines[] = "## {$component} {$meta['version']} — {$implemented}/{$specOpCount} operations implemented";
            $lines[] = '';

            if ($uncovered === []) {
                $lines[] = '_Fully covered._';
            } else {
                sort($uncovered);
                foreach ($uncovered as $operation) {
                    $lines[] = "- {$operation}";
                }
            }

            $lines[] = '';
        }

        $lines[] = '## Unimplemented components';
        $lines[] = '';
        if (self::UNIMPLEMENTED_COMPONENTS === []) {
            $lines[] = '- None: all core ZGW components are implemented.';
        }
        foreach (self::UNIMPLEMENTED_COMPONENTS as $component) {
            $lines[] = "- {$component}: not supported by this package.";
        }
        $lines[] = '';

        $dir = dirname(__DIR__, 2).'/build';
        if (! is_dir($dir)) {
            mkdir($dir, 0o775, true);
        }

        $report = $dir."/zgw-coverage-{$release}.md";
        file_put_contents($report, implode("\n", $lines)."\n");

        $this->assertFileExists($report);
        $this->assertGreaterThan(0, $totalSpecOps, "No operations were read from the ZGW {$release} specs.");
        $this->assertGreaterThan(0, $totalCovered, "The client covers no operations in ZGW {$release}; the registry or path matching is likely broken.");
    }

    /**
     * Registry operations grouped by component as normalized "method path" signatures.
     *
     * @return array<string, list<string>>
     */
    private function registryByComponent(): array
    {
        $grouped = [];

        foreach (OperationRegistry::all() as $operation) {
            $grouped[$operation['component']][] = strtolower($operation['method']).' '.$this->normalize($operation['path']);
        }

        return $grouped;
    }

    private function normalize(string $path): string
    {
        return (string) preg_replace('/\{[^}]+\}/', '{}', $path);
    }
}
