<?php

declare(strict_types=1);

namespace Woweb\Zgw\Tests\Contract;

use PHPUnit\Framework\Attributes\DataProvider;
use Woweb\Zgw\Tests\Contract\Support\OperationRegistry;
use Woweb\Zgw\Tests\Contract\Support\ReleaseMatrix;

/**
 * Enforces full coverage: for every supported release, the client must implement every CRUD
 * operation (GET/POST/PUT/PATCH/DELETE; HEAD/OPTIONS/TRACE mirror GET and are never issued) that
 * the release's OpenAPI spec defines. Any uncovered operation fails the test. A coverage report is
 * also written to build/zgw-coverage-{release}.md for reference.
 */
final class CoverageReportTest extends ContractTestCase
{
    /**
     * @return iterable<string, array{0: string}>
     */
    public static function releaseProvider(): iterable
    {
        foreach (array_keys(ReleaseMatrix::releases()) as $release) {
            yield "ZGW {$release}" => [$release];
        }
    }

    #[DataProvider('releaseProvider')]
    public function test_writes_coverage_report(string $release): void
    {
        $components = ReleaseMatrix::releases()[$release]['components'];

        // Each contract CI job fetches only its own release's specs, so skip a release whose
        // fixtures are not present (matching the per-operation contract tests).
        $available = array_filter(
            array_keys($components),
            fn (string $component): bool => ReleaseMatrix::specFile($release, $component) !== null,
        );

        if ($available === []) {
            $this->markTestSkipped("ZGW {$release} specs are not present in this run.");
        }

        $registry = $this->registryByComponent($release);

        $lines = [
            "# ZGW {$release} coverage report",
            '',
            'Spec operations not implemented by this package. Generated by the contract test suite.',
            '',
        ];

        $totalSpecOps = 0;
        $allUncovered = [];

        foreach ($components as $component => $meta) {
            $specFile = ReleaseMatrix::specFile($release, $component);

            if ($specFile === null) {
                continue;
            }

            $spec = $this->loadSpec($release, $component);
            $covered = $registry[$component] ?? [];

            $uncovered = [];
            $specOpCount = 0;

            foreach ($spec->operations() as $operation) {
                // Only count operations the client could meaningfully implement; HEAD/OPTIONS/TRACE
                // mirror GET metadata and are never issued by this package.
                if (! in_array(strtolower($operation['method']), ['get', 'post', 'put', 'patch', 'delete'], true)) {
                    continue;
                }

                $specOpCount++;
                $signature = strtolower($operation['method']).' '.$this->normalize($operation['path']);

                if (! in_array($signature, $covered, true)) {
                    $uncovered[] = strtoupper($operation['method']).' '.$operation['path'];
                    $allUncovered[] = "{$component}: ".strtoupper($operation['method']).' '.$operation['path'];
                }
            }

            $totalSpecOps += $specOpCount;
            $implemented = $specOpCount - count($uncovered);

            $lines[] = "## {$component} {$meta['version']} — {$implemented}/{$specOpCount} operations implemented";
            $lines[] = '';

            if ($uncovered === []) {
                $lines[] = '_Fully covered._';
            } else {
                sort($uncovered);
                foreach ($uncovered as $operation) {
                    $lines[] = "- {$operation}";
                }
            }

            $lines[] = '';
        }

        $dir = dirname(__DIR__, 2).'/build';
        if (! is_dir($dir)) {
            mkdir($dir, 0o775, true);
        }

        $report = $dir."/zgw-coverage-{$release}.md";
        file_put_contents($report, implode("\n", $lines)."\n");

        $this->assertGreaterThan(0, $totalSpecOps, "No operations were read from the ZGW {$release} specs.");
        $this->assertSame(
            [],
            $allUncovered,
            "ZGW {$release} has ".count($allUncovered).' uncovered spec operation(s); the client must implement all of them:'.
            "\n  - ".implode("\n  - ", $allUncovered)
        );
    }

    /**
     * Registry operations available in the given release, grouped by component as normalized
     * "method path" signatures.
     *
     * @return array<string, list<string>>
     */
    private function registryByComponent(string $release): array
    {
        $grouped = [];

        foreach (OperationRegistry::all() as $operation) {
            if (! in_array($release, $operation['versions'], true)) {
                continue;
            }

            $grouped[$operation['component']][] = strtolower($operation['method']).' '.$this->normalize($operation['path']);
        }

        return $grouped;
    }

    private function normalize(string $path): string
    {
        return (string) preg_replace('/\{[^}]+\}/', '{}', $path);
    }
}
