<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Autorisaties;

use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Applicatie.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write autorisaties:Applicatie
 */
final class ApplicatieWrite extends WriteBuilder
{
    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function clientIds(?array $value): static
    {
        return $this->set('clientIds', $value);
    }

    public function label(?string $value): static
    {
        return $this->set('label', $value);
    }

    public function heeftAlleAutorisaties(?bool $value): static
    {
        return $this->set('heeftAlleAutorisaties', $value);
    }

    public function alleenIsGereedVoorPublicatie(?bool $value): static
    {
        return $this->set('alleenIsGereedVoorPublicatie', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function autorisaties(?array $value): static
    {
        return $this->set('autorisaties', $value);
    }
}
