<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Notificaties;

use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Kanaal.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write notificaties:Kanaal
 */
final class KanaalWrite extends WriteBuilder
{
    public function naam(?string $value): static
    {
        return $this->set('naam', $value);
    }

    public function documentatieLink(Reference|string|null $value): static
    {
        return $this->set('documentatieLink', $this->reference($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function filters(?array $value): static
    {
        return $this->set('filters', $value);
    }
}
