<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Besluiten;

use DateTimeInterface;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Besluit.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write besluiten:Besluit
 */
final class BesluitWrite extends WriteBuilder
{
    public function identificatie(?string $value): static
    {
        return $this->set('identificatie', $value);
    }

    public function verantwoordelijkeOrganisatie(?string $value): static
    {
        return $this->set('verantwoordelijkeOrganisatie', $value);
    }

    public function besluittype(Reference|string|null $value): static
    {
        return $this->set('besluittype', $this->reference($value));
    }

    public function zaak(Reference|string|null $value): static
    {
        return $this->set('zaak', $this->reference($value));
    }

    public function datum(DateTimeInterface|string|null $value): static
    {
        return $this->set('datum', $this->date($value));
    }

    public function toelichting(?string $value): static
    {
        return $this->set('toelichting', $value);
    }

    public function bestuursorgaan(?string $value): static
    {
        return $this->set('bestuursorgaan', $value);
    }

    public function ingangsdatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('ingangsdatum', $this->date($value));
    }

    public function vervaldatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('vervaldatum', $this->date($value));
    }

    public function vervalreden(?string $value): static
    {
        return $this->set('vervalreden', $value);
    }

    public function publicatiedatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('publicatiedatum', $this->date($value));
    }

    public function verzenddatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('verzenddatum', $this->date($value));
    }

    public function uiterlijkeReactiedatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('uiterlijkeReactiedatum', $this->date($value));
    }
}
