<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Zaken;

use DateTimeInterface;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a KlantContact.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write zaken:KlantContact
 */
final class KlantContactWrite extends WriteBuilder
{
    public function zaak(Reference|string|null $value): static
    {
        return $this->set('zaak', $this->reference($value));
    }

    public function identificatie(?string $value): static
    {
        return $this->set('identificatie', $value);
    }

    public function datumtijd(DateTimeInterface|string|null $value): static
    {
        return $this->set('datumtijd', $this->dateTime($value));
    }

    public function kanaal(?string $value): static
    {
        return $this->set('kanaal', $value);
    }

    public function onderwerp(?string $value): static
    {
        return $this->set('onderwerp', $value);
    }

    public function toelichting(?string $value): static
    {
        return $this->set('toelichting', $value);
    }
}
