<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Zaken;

use Woweb\Zgw\Data\Generated\Zaken\Enums\BetrokkeneType;
use Woweb\Zgw\Data\Generated\Zaken\Enums\IndicatieMachtiging;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Rol.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write zaken:Rol
 */
final class RolWrite extends WriteBuilder
{
    public function zaak(Reference|string|null $value): static
    {
        return $this->set('zaak', $this->reference($value));
    }

    public function betrokkene(Reference|string|null $value): static
    {
        return $this->set('betrokkene', $this->reference($value));
    }

    public function betrokkeneType(BetrokkeneType|string|int|null $value): static
    {
        return $this->set('betrokkeneType', $this->enum($value));
    }

    public function afwijkendeNaamBetrokkene(?string $value): static
    {
        return $this->set('afwijkendeNaamBetrokkene', $value);
    }

    public function roltype(Reference|string|null $value): static
    {
        return $this->set('roltype', $this->reference($value));
    }

    public function roltoelichting(?string $value): static
    {
        return $this->set('roltoelichting', $value);
    }

    public function indicatieMachtiging(IndicatieMachtiging|string|int|null $value): static
    {
        return $this->set('indicatieMachtiging', $this->enum($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function contactpersoonRol(?array $value): static
    {
        return $this->set('contactpersoonRol', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function _expand(?array $value): static
    {
        return $this->set('_expand', $value);
    }
}
