<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Zaken;

use DateTimeInterface;
use Woweb\Zgw\Data\Generated\Zaken\Enums\Archiefnominatie;
use Woweb\Zgw\Data\Generated\Zaken\Enums\Archiefstatus;
use Woweb\Zgw\Data\Generated\Zaken\Enums\Betalingsindicatie;
use Woweb\Zgw\Data\Generated\Zaken\Enums\Vertrouwelijkheidaanduiding;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a Zaak.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write zaken:Zaak
 */
final class ZaakWrite extends WriteBuilder
{
    public function identificatie(?string $value): static
    {
        return $this->set('identificatie', $value);
    }

    public function bronorganisatie(?string $value): static
    {
        return $this->set('bronorganisatie', $value);
    }

    public function omschrijving(?string $value): static
    {
        return $this->set('omschrijving', $value);
    }

    public function toelichting(?string $value): static
    {
        return $this->set('toelichting', $value);
    }

    public function zaaktype(Reference|string|null $value): static
    {
        return $this->set('zaaktype', $this->reference($value));
    }

    public function registratiedatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('registratiedatum', $this->date($value));
    }

    public function verantwoordelijkeOrganisatie(?string $value): static
    {
        return $this->set('verantwoordelijkeOrganisatie', $value);
    }

    public function startdatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('startdatum', $this->date($value));
    }

    public function einddatumGepland(DateTimeInterface|string|null $value): static
    {
        return $this->set('einddatumGepland', $this->date($value));
    }

    public function uiterlijkeEinddatumAfdoening(DateTimeInterface|string|null $value): static
    {
        return $this->set('uiterlijkeEinddatumAfdoening', $this->date($value));
    }

    public function publicatiedatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('publicatiedatum', $this->date($value));
    }

    public function communicatiekanaal(Reference|string|null $value): static
    {
        return $this->set('communicatiekanaal', $this->reference($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function productenOfDiensten(?array $value): static
    {
        return $this->set('productenOfDiensten', $value);
    }

    public function vertrouwelijkheidaanduiding(Vertrouwelijkheidaanduiding|string|int|null $value): static
    {
        return $this->set('vertrouwelijkheidaanduiding', $this->enum($value));
    }

    public function betalingsindicatie(Betalingsindicatie|string|int|null $value): static
    {
        return $this->set('betalingsindicatie', $this->enum($value));
    }

    public function laatsteBetaaldatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('laatsteBetaaldatum', $this->dateTime($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function zaakgeometrie(?array $value): static
    {
        return $this->set('zaakgeometrie', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function verlenging(?array $value): static
    {
        return $this->set('verlenging', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function opschorting(?array $value): static
    {
        return $this->set('opschorting', $value);
    }

    public function selectielijstklasse(Reference|string|null $value): static
    {
        return $this->set('selectielijstklasse', $this->reference($value));
    }

    public function hoofdzaak(Reference|string|null $value): static
    {
        return $this->set('hoofdzaak', $this->reference($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function relevanteAndereZaken(?array $value): static
    {
        return $this->set('relevanteAndereZaken', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function kenmerken(?array $value): static
    {
        return $this->set('kenmerken', $value);
    }

    public function archiefnominatie(Archiefnominatie|string|int|null $value): static
    {
        return $this->set('archiefnominatie', $this->enum($value));
    }

    public function archiefstatus(Archiefstatus|string|int|null $value): static
    {
        return $this->set('archiefstatus', $this->enum($value));
    }

    public function archiefactiedatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('archiefactiedatum', $this->date($value));
    }

    public function opdrachtgevendeOrganisatie(?string $value): static
    {
        return $this->set('opdrachtgevendeOrganisatie', $value);
    }

    public function processobjectaard(?string $value): static
    {
        return $this->set('processobjectaard', $value);
    }

    public function startdatumBewaartermijn(DateTimeInterface|string|null $value): static
    {
        return $this->set('startdatumBewaartermijn', $this->date($value));
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function processobject(?array $value): static
    {
        return $this->set('processobject', $value);
    }
}
