<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Zaken;

use DateTimeInterface;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a ZaakInformatieObject.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write zaken:ZaakInformatieObject
 */
final class ZaakInformatieObjectWrite extends WriteBuilder
{
    public function informatieobject(Reference|string|null $value): static
    {
        return $this->set('informatieobject', $this->reference($value));
    }

    public function zaak(Reference|string|null $value): static
    {
        return $this->set('zaak', $this->reference($value));
    }

    public function titel(?string $value): static
    {
        return $this->set('titel', $value);
    }

    public function beschrijving(?string $value): static
    {
        return $this->set('beschrijving', $value);
    }

    public function vernietigingsdatum(DateTimeInterface|string|null $value): static
    {
        return $this->set('vernietigingsdatum', $this->dateTime($value));
    }

    public function status(Reference|string|null $value): static
    {
        return $this->set('status', $this->reference($value));
    }
}
