<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Zaken;

use Woweb\Zgw\Data\Generated\Zaken\Enums\ObjectType;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a ZaakObject.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write zaken:ZaakObject
 */
final class ZaakObjectWrite extends WriteBuilder
{
    public function zaak(Reference|string|null $value): static
    {
        return $this->set('zaak', $this->reference($value));
    }

    public function object(Reference|string|null $value): static
    {
        return $this->set('object', $this->reference($value));
    }

    public function zaakobjecttype(Reference|string|null $value): static
    {
        return $this->set('zaakobjecttype', $this->reference($value));
    }

    public function objectType(ObjectType|string|int|null $value): static
    {
        return $this->set('objectType', $this->enum($value));
    }

    public function objectTypeOverige(?string $value): static
    {
        return $this->set('objectTypeOverige', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function objectTypeOverigeDefinitie(?array $value): static
    {
        return $this->set('objectTypeOverigeDefinitie', $value);
    }

    public function relatieomschrijving(?string $value): static
    {
        return $this->set('relatieomschrijving', $value);
    }

    /**
     * @param  array<array-key, mixed>|null  $value
     */
    public function _expand(?array $value): static
    {
        return $this->set('_expand', $value);
    }
}
