<?php

declare(strict_types=1);

// This file is generated by `composer dto:generate`. Do not edit it by hand.

namespace Woweb\Zgw\Data\Writes\Zaken;

use Woweb\Zgw\Data\Generated\Zaken\Enums\NotitieType;
use Woweb\Zgw\Data\Generated\Zaken\Enums\Status;
use Woweb\Zgw\Data\Values\Reference;
use Woweb\Zgw\Data\Writes\WriteBuilder;

/**
 * Builds a create or update payload for a ZaakNotitie.
 *
 * Only fields you set end up in toPayload(), so the same builder is safe for a PATCH (set
 * just the fields you want to change) and for a create. Set a field to null to clear it on a
 * PATCH. Setters carry the writable (not readOnly) fields across releases 1.5, 1.6, 1.7.
 *
 * @zgw-write zaken:ZaakNotitie
 */
final class ZaakNotitieWrite extends WriteBuilder
{
    public function onderwerp(?string $value): static
    {
        return $this->set('onderwerp', $value);
    }

    public function tekst(?string $value): static
    {
        return $this->set('tekst', $value);
    }

    public function aangemaaktDoor(?string $value): static
    {
        return $this->set('aangemaaktDoor', $value);
    }

    public function notitieType(NotitieType|string|int|null $value): static
    {
        return $this->set('notitieType', $this->enum($value));
    }

    public function status(Status|string|int|null $value): static
    {
        return $this->set('status', $this->enum($value));
    }

    public function gerelateerdAan(Reference|string|null $value): static
    {
        return $this->set('gerelateerdAan', $this->reference($value));
    }
}
